### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by avin-kavish** [riktar/uncino#3]
What does this do?

**Comment by riktar** [comment]
It's a hook system, similar to WordPress hook system for make core codebase pluggable. Read
the readme of the repo for docs and philosophy:)

**Comment by avin-kavish** [comment]
I did. But I'm not clear on how it is useful

**Comment by avin-kavish** [comment]
Can you show a real world example?

**Comment by riktar** [comment]
A simple example: 

You have a function that create a user in a db, after a few day you add an action that when a user was inserted the system will send an email to the user. 

After a couple of days when a user was inserted you want also send him a tweet.

With Uncino all this actions can be write in hooks and call in one place, so if you want add some new features yuor core code is clean and always pluggable instead of edit core code and add bugs or regressions.
